set nocompatible 
set number 				"Нумерация строк"
set hidden 				"Разрешить скрытые буферы"
set tabstop=4			"Размер шага табуляции 4"
set shiftwidth=4
set mouse=r

set ignorecase
set smartcase
set hlsearch
set incsearch

set colorcolumn=111
"set smartindent			""автоматически ставит отступы в нужных местах "

set textwidth=111
set wrapmargin=111

"VIM-PLUG BLOCK"
	call plug#begin()

		"FileManager"
			Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }	
	
		"Syntax" 
			Plug 'sheerun/vim-polyglot'

		"PairedBrackets"
			Plug 'jiangmiao/auto-pairs'

		"ColorSchemes"
			Plug 'flazz/vim-colorschemes'

		"BufTabLine"
			Plug 'ap/vim-buftabline' 
		
		"EmmetVim"
			Plug 'mattn/emmet-vim'


	call plug#end()

"HOTKEYS"
	
	"File Manager Display ON/OFF"
	
		map <silent> <C-F> :NERDTreeToggle<CR>	

	"BufTabLine Move"
		nnoremap <C-P> :bnext<CR>
		nnoremap <C-O> :bprev<CR>
		nnoremap <C-D> :bw<CR>
		nnoremap <C-X> :bd<CR>

	"ON/OFF AutoPairs"0
		let g:AutoPairsShortcutToggle = '<C-L>' 

	"Emmet Mod Key"
		let g:user_emmet_leader_key='<C-M>'

		let g:user_emmet_install_global = 0
		autocmd FileType html,css EmmetInstall
"APPEARANCE"

	"THEMES"

		"colorscheme PerfectDark"
		colorscheme monokain"	

	"BACKGROUND"
	
		:hi Normal guibg=NONE ctermbg=NONE"
		
	"TABS"
	
		hi TabLine      ctermfg=White  ctermbg=Black     cterm=NONE"
		hi TabLineFill  ctermfg=White  ctermbg=Black     cterm=NONE"
		hi TabLineSel   ctermfg=White  ctermbg=DarkGray  cterm=NONE"

	"NERDTreeToggle SIZE"
